### ISSUE TITLE
reflect asset to assets migration in python driver

### ISSUE THREAD

**Issue by LaurentMontBlanc** [planetmint/planetmint-driver-python#20]
## Description
This issue is created to reflect the migration to the `v3.0` schema, which focuses on the multi-asset support.
NOTE: The `planetmint` service in `docker-compose.yml` needs to know which branch to build. replace `main` with `asset-migration`. 

## ToDos
- Adjust `asset` references in `offchain.py`, `driver.py`, `common/transaction.py`
- Ajdust `asset` references in test suite
- Watch test suite collapse and take notes
- Fix test cases and run accaptence/integration tests on `planetmint@asset-migration`

**Comment by LaurentDeMontBlanc** [comment]
The remaining test cases fail because they send a GET request to `/transactions`. Currently the `/transactions` route takes `asset_id` as a query parameter (`str`) and then passes it to `lib.get_transactions_filtered`. That function then calls `get_txids_filtered` which expects `asset_ids` as a list of tx ids.

**Comment by LaurentDeMontBlanc** [comment]
There is not really a standardized way of passing arrays/lists as query params. I think the easiest solution is to pass them as a comma separated list like so: `?asset_ids=0e7a9a9047fdf39eb5ead7170ec412c6bffdbe8d7888966584b4014863e03518,107ec21f4c53cd2a934941010437ac74882161bcbefdfd7664268823fc347996`

**Comment by LaurentDeMontBlanc** [comment]
I've continued on the cryptoconditions and fixed all test, however 3 test cases in the entire test suit over all 3 projects fail seemingly at random. Not deterministically reproducable... I'm looking into it but I will also need time to write a PRP to document why this change was needed to move further into the project

**Comment by LaurentDeMontBlanc** [comment]
@ArpitShukla007 as mentioned in the comment above we have some test cases failing. could you please check out the behaviour on your machine and if you can replicate what happens on my machine (i.e.: sometimes every test passes, sometimes a single test per test suite fails).

So could you do the following for me:
- check out the `asset-migration` branch on each project (`planetmint`, `planetmint-python-driver`, `cryptoconditions`)
- run `make test` multiple times
- analyse what causes the issues

What I got so far:
- the failure on `cryptoconditions` and `planetmint/acceptance` tests is caused during the multiprocessing in `cryptoconditions/types/zenroom.py` where `run_zenroom` starts mutliple processes to `_execute` the `zencode`.
- the `TypeError` on the `planetmint-driver-python` test suite are probably caused by the `text_search_assets` fixture. I've marked it with a TODO comment

**Comment by LaurentDeMontBlanc** [comment]
@ArpitShukla007 I fixed the issue with the `text_search_assets`. It happened always on the first test run because the fixture was checking if the tx were already created and if not returned them in an old format instead of the new one.

**Comment by ArpitShukla007** [comment]
@LaurentDeMontBlanc I have fixed the issue of CI build. It happened due to the dependency version error, by default the Jinja2` v3.1.2` was being installed which I changed to `v3.0.0`.

**Comment by ArpitShukla007** [comment]
@LaurentDeMontBlanc Also, the docs were not updated from asset to assets and the change in data structure. I have added those changes wherever needed. Now, all the CI build issues are solved.
